<?php

namespace App\Console\Commands;
use Illuminate\Console\Command;

class SolrFullImport extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'solr:fullimport';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Sync full database chnages to solr.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }  

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $curl = curl_init();

    curl_setopt_array($curl, array(
      CURLOPT_URL => 'http://localhost:8983/solr/brands/dataimport?indent=on&wt=json',
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_VERBOSE=> 0,
      CURLOPT_CUSTOMREQUEST => 'POST',
      CURLOPT_POSTFIELDS =>'command=full-import&verbose=false&clean=true&commit=true&core=brands&name=dataimport',
    ));

    $response = curl_exec($curl);
    curl_close($curl);
    $this->info($response);
    }
}